version = 1

test_patterns = ["src/test/**"]

exclude_patterns = ["**/dropzone.js"]

[[analyzers]]
name = "javascript"
enabled = true

[[analyzers]]
name = "java"
enabled = true

  [analyzers.meta]
  runtime_version = "17"

[[transformers]]
name = "google-java-format"
enabled = true