spring:
  datasource:
    url: ${DATABASE_URL}
    driverClassName: org.postgresql.Driver
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 10m
          
mnit-filenet:
  enabled: false
          
feature-flag:
  certain-pops: off

demo: true
