CREATE TABLE research
(
    spoken_language          VARCHAR2(255),
    written_language         VARCHAR2(255),
    first_name               VARCHAR2(255),
    last_name                VARCHAR2(255),
    date_of_birth            DATE,
    sex                      VARCHAR2(255),
    phone_number             VARCHAR2(255),
    email                    VARCHAR2(255),
    phone_opt_in             NUMBER(1),
    email_opt_in             NUMBER(1),
    zip_code                 VARCHAR2(255),
    snap                     NUMBER(1),
    cash                     NUMBER(1),
    housing                  NUMBER(1),
    emergency                NUMBER(1),
    live_alone               NUMBER(1),
    money_made_last30_days   NUMBER(19,2),
    pay_rent_or_mortgage     NUMBER(1),
    home_expenses_amount     NUMBER(19,2),
    are_you_working          NUMBER(1),
    self_employment          NUMBER(1),
    social_security          NUMBER(1),
    ssi                      NUMBER(1),
    veterans_benefits        NUMBER(1),
    unemployment             NUMBER(1),
    workers_compensation     NUMBER(1),
    retirement               NUMBER(1),
    child_or_spousal_support NUMBER(1),
    tribal_payments          NUMBER(1),
    household_size           NUMBER(19,0),
    entered_ssn              NUMBER(1),
    flow                     VARCHAR2(255),
    application_id           VARCHAR2(255),
    county                   VARCHAR2(255)
);
