CREATE TABLE research
(
    spoken_language          VARCHAR,
    written_language         VARCHAR,
    first_name               VARCHAR,
    last_name                VARCHAR,
    date_of_birth            DATE,
    sex                      VARCHAR,
    phone_number             VARCHAR,
    email                    VARCHAR,
    phone_opt_in             BOOLEAN,
    email_opt_in             BOOLEAN,
    zip_code                 VARCHAR,
    snap                     BOOLEAN,
    cash                     BOOLEAN,
    housing                  BOOLEAN,
    emergency                BOOLEAN,
    live_alone               BOOLEAN,
    money_made_last30_days   NUMERIC,
    pay_rent_or_mortgage     BOOLEAN,
    home_expenses_amount     NUMERIC,
    are_you_working          BOOLEAN,
    self_employment          BOOLEAN,
    social_security          BOOLEAN,
    ssi                      BOOLEAN,
    veterans_benefits        BOOLEAN,
    unemployment             BOOLEAN,
    workers_compensation     BOOLEAN,
    retirement               BOOLEAN,
    child_or_spousal_support BOOLEAN,
    tribal_payments          BOOLEAN,
    household_size           INTEGER,
    entered_ssn              BOOLEAN,
    flow                     VARCHAR,
    application_id           VARCHAR,
    county                   VARCHAR
);
