name: Run Percy visual diff testing

on:
  schedule:
    - cron:  '0 0 * * *'
  workflow_dispatch:
    inputs: { }

jobs:
  percy:
    name: Run Percy
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: shiba
          POSTGRES_PASSWORD: shiba
          POSTGRES_DB: shiba-test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v2
    - name: Set up ChromeDriver
      uses: nanasess/setup-chromedriver@v1.0.1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '14'
    - name: Use Node.js 14.x
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: Install percy from npm
      run: npm install -g @percy/cli
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run journey test and send to Percy
      run: PERCY_TOKEN=${{ secrets.PERCY_TOKEN }} percy exec -- ./gradlew clean test --tests org.codeforamerica.shiba.pages.features.UserJourneyPageTest.userCanCompleteTheNonExpeditedHouseholdFlow
      env:
        S3_BUCKET: ${{ secrets.S3_TEST_BUCKET }}
        AWS_ACCESS_KEY: ${{ secrets.CLOUD_AWS_CREDENTIALS_ACCESS_KEY }}
        AWS_SECRET_KEY: ${{ secrets.CLOUD_AWS_CREDENTIALS_SECRET_KEY }}