name: Run Percy visual diff testing

on:
  schedule:
    - cron: '0 14 * * 1'
  workflow_dispatch:
    inputs: { }

jobs:
  percy:
    name: Run Percy
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_USER: shiba
          POSTGRES_PASSWORD: shiba
          POSTGRES_DB: shiba-test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - name: Set up ChromeDriver
        uses: nanasess/setup-chromedriver@v1.1.0
      - name: Set up JDK
        uses: actions/setup-java@v3.7.0
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'gradle'
      - name: Use Node.js 14.x
        uses: actions/setup-node@v3.5.1
        with:
          node-version: '14.x'
      - name: Install percy from npm
        run: npm install -g @percy/cli
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run journey test and send to Percy
        run: percy exec -- ./gradlew clean test --tests org.codeforamerica.shiba.journeys.FullFlowJourneyTest.fullApplicationWithDocumentUploads
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
      - name: Announce on Slack
        if: ${{ always() }}
        uses: innocarpe/actions-slack@v1
        with:
          status: ${{ job.status }}
          success_text: ':eyes: Check out new the Percy build: https://percy.io/8a855b2e/mnbenefits'
          failure_text: ':frowning: Percy build failed '
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
